### ISSUE TITLE
Automatically re-check the API key whenever the Settings page is reloaded

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#100]
Whenever the Settings page is reloaded...

- We should automatically re-check the API key so the user can change the Advanced SEO settings without having to click the Check button. 
- Hide the check button by default.
- When the check runs, we can use the same logic as [Issue #95](https://github.com/transifex/transifex-live-wordpress/issues/95).
- Unless the user enters a different API key, in which case we should show the Check button again.

**Comment by matthewjackowski** [comment]
Added the following states flows:
default if key exists -> hidden
default if key does not exist -> wait
default if key check error -> wait
change api text box -> button:wait
