### ISSUE TITLE
Update wording for plugin

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#105]
Make the following strings part of the template and changeable depending on whether Subdirectory or Subdomain has been selected: 

![image](https://cloud.githubusercontent.com/assets/2788702/13167072/362af260-d684-11e5-86db-34f4991f2e95.png)

**Comment by matthewjackowski** [comment]
@samuelchan22 they are available in the template here
https://github.com/transifex/transifex-live-wordpress/blob/devel/includes/admin/transifex-live-integration-settings-template.php#L38
and here
https://github.com/transifex/transifex-live-wordpress/blob/devel/includes/admin/transifex-live-integration-settings-template.php#L45
