### ISSUE TITLE
Save Changes button is not getting enabled

### ISSUE THREAD

**Issue by diegobz** [transifex/transifex-live-wordpress#109]
I added a valid key switched over the different radio button options, but the `Save Changes` button never got clickable.

Tested with latest devel (a1d27abd8b3c611661900f6d031e9472a3af461e)

![screen shot 2016-02-19 at 11 52 14 am](https://cloud.githubusercontent.com/assets/711654/13172772/7fe057aa-d702-11e5-9190-7ddef9d777c6.png)

**Comment by matthewjackowski** [comment]
@diegobz 1.2.2 patch has already been shipped
