### ISSUE TITLE
Language picker should be able to work with subdomains/subdirectories URL structures

### ISSUE THREAD

**Issue by diegobz** [transifex/transifex-live-wordpress#117]
When using subdomains or subdirectories URL structures, if enabled, the language picker should redirect people to URLs related to the selected language, instead of using the default behavior of replacing text in-place.

**Comment by matthewjackowski** [comment]
@diegobz please clarify where the language picker control should be enabled from.  Either in the WP admin screen or in Live admin.  And if it is Live, what jsonp file will I need to process in order to receive this information?

**Comment by diegobz** [comment]
@matthewjackowski from Live admin in Tx. You should be able to rely on `https://cdn.transifex.com/<key>/latest/settings.jsonp` to get the info from there into the plugin.

**Comment by matthewjackowski** [comment]
So now the api key will need to 'double tap' both transifex languages AND transifex settings.  If either fail then you will be blocked from continuing to setup the plugin and will not be allowed to save the apikey.
