### ISSUE TITLE
Archives rewrite links are throwing 404

### ISSUE THREAD

**Issue by diegobz** [transifex/transifex-live-wordpress#120]
Even though I have `el` published, the `/el/2016/01/` link is getting me a 404 page.

**Comment by matthewjackowski** [comment]
Recreated this issue.  It actually isn't all archives links as the title indicates, rewrites are missing specifically for monthnum/year and year.

**Comment by matthewjackowski** [comment]
Found the tricky bit in WP rewrites:
/*
		 * Create a list of dirs to walk over, making rewrite rules for each level
		 * so for example, a $structure of /%year%/%monthnum%/%postname% would create
		 * rewrite rules for /%year%/, /%year%/%monthnum%/ and /%year%/%monthnum%/%postname%
		 */
Since WP rewrite is not using hooked get_permastruct...lang is not inserted during walk.

**Comment by diegobz** [comment]
:+1:
