### ISSUE TITLE
API key value becomes null after logging out of WP

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#123]
Here are the steps I took:

1. Add API key through plugin (I'm using the version from devel), leaving Advanced SEO settings disabled. Everything works properly at this point. You can see the API key when you view page source. The sidebar can also be triggered.
2. Log out of WP.
3. View page source shows null.
4. API key reappears once you log into WP again.

![image](https://cloud.githubusercontent.com/assets/2788702/13587657/90b32e84-e47e-11e5-9b0c-b1b210141cbe.png)

**Comment by matthewjackowski** [comment]
I believe this is due to caching.

**Comment by diegobz** [comment]
@samuelchan22 May be worth creating a FAQ about such things that others can run into as well.
