### ISSUE TITLE
Links for categories, archive and tags are not obeying URL structure

### ISSUE THREAD

**Issue by diegobz** [transifex/transifex-live-wordpress#127]
Check it out in the sidebar menu: http://wp.transifex.live/pt-br/blog/introducing-the-plugin/
Theme: https://wordpress.org/themes/optimizer/

**Comment by matthewjackowski** [comment]
Loaded optimizer theme, change permalink settings to custom with blog:
![image](https://cloud.githubusercontent.com/assets/974299/13757724/21a90fb2-e9e3-11e5-9a0d-7f3d7fe50524.png)

Reverse links still work...maybe there is a diff in content on your site?  Closing for now.
