### ISSUE TITLE
Add more descriptive text to the plugin settings

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#13]
It's unclear what some of the fields in the settings are for:

* Parse attributes
* Classes
* Tags
* Language picker ID
* "Enable" checkbox (should probably say "Enable custom language picker styling").

We should add help text and/or link to documentation (in-progress).

**Comment by matthewjackowski** [comment]
These fields have beenremoved in favor of setting instead in the Transifex Live dashboard
