### ISSUE TITLE
UI for prerender stuff

### ISSUE THREAD

**Issue by diegobz** [transifex/transifex-live-wordpress#141]
The prerender option should be available only when subdomain or subdirectory are enabled
![tx-live-wp-admin](https://cloud.githubusercontent.com/assets/711654/14191875/253a711a-f74f-11e5-8145-59c684dc3e45.png)

**Comment by matthewjackowski** [comment]
![Sample UI](https://raw.githubusercontent.com/transifex/transifex-live-wordpress/devel/sample-ui/wp-plugin-prerender-ui.gif "Sample UI Screencast")
