### ISSUE TITLE
Author redirect isn't working

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#149]
I'm on the Portuguese site but when I hover over the author name (Sam) that's under the title of the blog post, you can see that the URL is pointing back to the English site (look at bottom of screenshot).  

![image](https://cloud.githubusercontent.com/assets/2788702/14470551/ff9fa17e-009e-11e6-8385-5cf19de90edf.png)

And subdirectories was enabled for Authors.

![image](https://cloud.githubusercontent.com/assets/2788702/14470602/44cd5f84-009f-11e6-911b-0e4e67850c60.png)

**Comment by matthewjackowski** [comment]
I can't recreate this issue...it's likely due to how the template is generating the link.  If native author functions are used it changes: 
![image](https://cloud.githubusercontent.com/assets/974299/14693915/4f5a6706-0718-11e6-967b-27b04389c97f.png)
