### ISSUE TITLE
Missing /languages folder and translations files

### ISSUE THREAD

**Issue by fxbenard** [transifex/transifex-live-wordpress#170]
Need to add the translations folder and all the languages files from TX. The ressource needs to be update there alse with the auto fetch feature.

**Comment by matthewjackowski** [comment]
@fxbenard 
I added languages to gitignore since that folder is 'generated' via grunt.  Ideally this content shouldn't be checked in as source.
Would a reasonable alternative to run the grunt targets on Travis CI instead?

The build process around this plugin has evolved significantly and now most of it is automated.

**Comment by fxbenard** [comment]
Ok, that's why. That's not ideal to grab the pot from GH. Is the ressource update in the automated process? The file on TX seems outdated.  I have no idea about the Travis CI.
Out of subject: Lots of files should be removed from the release package as well I think.

**Comment by matthewjackowski** [comment]
You can see the automation here: https://travis-ci.org/transifex/transifex-live-wordpress
The Travis automation has some issues running tx client, so, no it's not running the tx-push atm, but it will shortly :)
Once the resource is kept updated in Transifex (via tx-push) is there a reason that the pot needs to be available in GH?  Another alternative is that I can check it back into GitHub into a different branch that Travis ignores.  But my thought is to manage it all through Transifex.

For releasing, Travis creates a new file directory tree and then runs svn to check it into WP.org.  There's no sense in storing a production 'build' in GH when you can always just retrieve it there.

**Comment by matthewjackowski** [comment]
Ok, tx-push is running on Travis-CI
