### ISSUE TITLE
Integrate with SEO for translations

### ISSUE THREAD

**Issue by matthewjackowski** [transifex/transifex-live-wordpress#19]
It would be useful for the plugin to integrate with Yoast SEO or other plugin to support translations in SEO keywords and meta.

**Comment by samuelchan22** [comment]
Transifex Live already picks up meta descriptions and such. Would this lead to duplicate content inside a Tx project?

**Comment by matthewjackowski** [comment]
I think if we determine that the Javascript detection works well...we can close this issue.

**Comment by matthewjackowski** [comment]
Javascript detection works...closing
