### ISSUE TITLE
Preview localized content

### ISSUE THREAD

**Issue by matthewjackowski** [transifex/transifex-live-wordpress#21]
It would be useful to extend preview mode to allow picking a language and then previewing the localized post in that language prior to publishing the post.

**Comment by matthewjackowski** [comment]
This should be supported with the Live sidebar...no changes to the plugin should be needed.  @dimoschi can you verify this?

**Comment by matthewjackowski** [comment]
Pinging this again...after conversation with @dimoschi maybe we could get @nikos @tabac or @ollandos to take a look.  Nothing major is needed just to verify that the sidebar works as intended with Wordpress preview.

**Comment by diegobz** [comment]
We have the sidebar now. Closing as wontfix.
