### ISSUE TITLE
Feedback on 1.0.3 v2

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#22]
1. Do we need to update the link in the plugin and its UTM parameters? Saw a comment in your Google Spreadsheet about deprecating that format. I've also been using this format for the other integrations links: https://docs.google.com/a/indifex.com/spreadsheets/d/1T4zaX72YG1uRlf4Mzpg3DFxDEPcGAFmaXhUl2dGEgAg/edit?usp=sharing.
2. Should we rename "Transifex API Key" to "Transifex Live API Key"? Is an API key required for our normal API? If not, then ignore this :)
3. What does checking the "Is this a staging server" box do? My understanding is that the staging content is a subset of content from the production server, i.e. they're the same resource, but the production URL is treated as the "primary" domain.
4. For the styling section, I'd suggest moving the "Enable" box before all the color fields. And maybe change the wording to something like "Enable custom language picker styling". And not sure if it's possible, but it'd be great to deactivate those color fields until someone checks that box.
5. For the color fields, it's not super clear to me what the accent and menu options are... but not sure we can do anything about that.

**Comment by matthewjackowski** [comment]
@samuelchan22 great stuff...moving forward please break these up into separate issues.

**Comment by matthewjackowski** [comment]
1 - Let me know what utms you want and I can update.
2 - Done
3 - It sets: window.liveSettings={"staging":1} for the live.js
4 - Partially complete, the control needs to be refactored to support an expanded label and a disabled state.  I'm not opposed, but let's move it to a separate issue.
5 - see below:
.txlive-langselector { color: <TEXT> }
.txlive-langselector .txlive-langselector-toggle { border-color: <ACCENT> }
.txlive-langselector-bottomright .txlive-langselector-marker, .txlive-langselector-bottomleft .txlive-langselector-marker { border-bottom-color: <TEXT> }
.txlive-langselector-topright .txlive-langselector-marker, .txlive-langselector-topleft .txlive-langselector-marker { border-top-color: <TEXT>  }
.txlive-langselector-list { background-color: <MENU> color: <LANGUAGE> }

**Comment by samuelchan22** [comment]
@matthewjackowski For 1, let's use this:

https://www.transifex.com/signup/?utm_source=live-plugin&utm_campaign=int-wp
