### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by RumenGeorgieff** [transifex/transifex-live-wordpress#34]
When I try to activate the plugin I get this error "Parse error: syntax error, unexpected '[' in /home/user/site.com/wp-content/plugins/transifex-live-integration/transifex-live-integration.php on line 24"

**Comment by matthewjackowski** [comment]
@RumenGeorgieff can you verify the version of the plugin you are using (1.0.5 is the latest) and the versions of Wordpress and PHP ?

**Comment by matthewjackowski** [comment]
Is it possible that you are running a PHP version < 5.4.0 ?

**Comment by matthewjackowski** [comment]
Hi @RumenGeorgieff! So I believe the issue is due to an older version of PHP.  Please try an older version of the plugin here: https://downloads.wordpress.org/plugin/transifex-live-integration.1.0.2.zip and see if that works for you.
