### ISSUE TITLE
Update admin interface to allow control of language rewrites

### ISSUE THREAD

**Issue by matthewjackowski** [transifex/transifex-live-wordpress#35]
This is an updated UI to allow admin control of Wordpress language rewrites (aka permalinks).

**Comment by matthewjackowski** [comment]
![image](https://cloud.githubusercontent.com/assets/974299/11851912/11e295ba-a3ea-11e5-9838-def3207674ff.png)

**Comment by diegobz** [comment]
1. We need to have distinct URLs for localized pages (example.com/product/ and example.com/fr/product/)

2.  Add META hreflang in `<head>` for all published languages from Live. (This requires some short of a sync button in WP)

**Comment by matthewjackowski** [comment]
Let's keep this issue focused on UI.  I'll create separate issues for your 2 points.

**Comment by samuelchan22** [comment]
@matthewjackowski Some thoughts:

**SEO / URLs**
1. It's not totally clear just from looking at the language URLs how they work. Based on the thread in Slack, it might be worth it to separate out how URLs behave for pages vs. posts. I'm guessing pages are more likely to be localized and posts are going to have more edge cases. 
2. For the mapping of project languages to localized subdirectories, one idea that comes to mind is to have two columns. In the left column, the list of project languages displayed (i.e. not a text field), and to the right of each language, a second column with the URL pattern which the user can change. And then somewhere, we should explain what this option means, e.g "Localized versions of your pages will live under www.example.com/fr/product/" or something like that.

**General**
1. The color fields should be disabled / grayed out until the checkbox is selected.

**Comment by matthewjackowski** [comment]
![transifex_live_ _test-wp-plugin_ _wordpress](https://cloud.githubusercontent.com/assets/974299/11910623/e2e25be8-a5af-11e5-8782-94fd8754eee3.jpg)

@samuelchan22 check it out!

**Comment by matthewjackowski** [comment]
The default codes are initially pulled from Live...but they can be updated and saved within Wordpress.

**Comment by matthewjackowski** [comment]
Also note that based on prior feedback, I created a new issue here: https://github.com/transifex/transifex-live-wordpress/issues/40

I need to investigate options to 'disable' those pickboxes as they use a library that ships with Wordpress...it might be non-trivial css.

**Comment by matthewjackowski** [comment]
@samuelchan22 another thing to consider is that currently the 'enable' checkbox causes the rewrites to happen and flushes the cache (instantly changing urls across the site).  I found in testing...this can be pretty catastrophic with the 'to all URLs' option.  It might be a good idea to put a separate button that 'activates' the rewrites (ie performs a cache flush).  Such that you can setup and save your settings first then hit the button.

**Comment by samuelchan22** [comment]
@matthewjackowski good stuff! That was quick! 

For the rewrites, we definitely need to protect the user from messing things up really badly, though I'm not sure if having them hit two buttons is the right approach given that it's a more confusing flow when you *do* actually want to change the settings. The less text someone has to read to understand what's happening or what to do, the better.

Some other thoughts based on the screenshot, and things I'll give more thought to as well:
1. The dropdowns might lead to users to think those are clickable when they're not. Is there another UI element we could use?
2. Since we show the source language, we should also show the URL paths for the English site compared to the translated sites. I'll try to think of something.

**Comment by matthewjackowski** [comment]
for 1...I used comboboxes because this allows you to use a different value then the 'value'...as we are saving the locale to the WP db and not the name.  I could simply remove the arrows with CSS.

for 2 this brings up a good question...currently source paths would all be rewritten with the source locale....this might not always be desirable (ie www.transifex.com/en/mypage ).  We might need some config options around this as well (I'm thinking more radio button selectors).

**Comment by diegobz** [comment]
I think the following field should be a dropdown menu. I don't think having the radio button and the check boxes depending on it a good UX.
![screen shot 2015-12-30 at 12 17 43 pm](https://cloud.githubusercontent.com/assets/711654/12051813/77f1a4bc-aeef-11e5-9c64-c920772b7860.png)

It should have the following options:

* Disabled.
* To all URLs.
* To page URLs only.

We should also have a help text explaining what the heck this is about. Something like: 

`Enabling this options your website will be able to serve localized content having distinct URLs using the language code as a root directory in the URL path. Ex: domain.com/fr/.`

**Comment by diegobz** [comment]
`File: transifex-live-integration.php - Line #: 88
Class: Transifex_Live_Integration_Rewrite - Function: __construct
Type: method call - Parameters: Array ( [0] => Array ( [api_key] => 2174190df36b4b76a7e152b70d6e8d00 [staging] => 0 [enable_frontend_css] => 0 [enable_language_urls] => 1 [add_language_rewrites] => 0 [source_language] => [raw_transifex_languages] => transifex_languages({\"timestamp\": \"1446155805.8\"}); [languages] => [language_lookup] => null [custom_picker_id] => ) )
Severity: 2 File: transifex-live-integration-rewrite.php Line: 31: strpos(): Empty needle`

**Comment by matthewjackowski** [comment]
Looks like you don't have any languages published as the Transifex Javascript is returning this: transifex_languages({\"timestamp\": \"1446155805.8\"}); 

I'll add some error handling regex for this case...but the better design solution is to have a real API rather than trying to parse a javascript file...see this issue: https://github.com/transifex/transifex-live-wordpress/issues/41

That HTML debug sure comes in handy!

**Comment by diegobz** [comment]
I think the error may have being related to having 2 plugins installed at once. Removing the old one seems to get it to use the correct key.

Now I facing a problem of getting a 404 while accessing http://wp.transifexdev.net/pt-br/, even though it seems I have everything setup correctly:

![screen shot 2015-12-30 at 4 31 56 pm](https://cloud.githubusercontent.com/assets/711654/12055315/2b34c914-af13-11e5-94f6-0cb921de7cf5.png)

#41 is not a blocker. We can keep going without it for now.

**Comment by matthewjackowski** [comment]
Looks like you didn't pick an option on the radio buttons.  I have a new version with a dropdown instead...let me get that wired in and you can try again...hopefully it will make the UI easier.

Also you shouldn't be able to install the plugin twice...if you can replicate that please let me know so I can check that installation is working properly.

**Comment by matthewjackowski** [comment]
Latest version screenshot...keep in mind that languages controls will not show up until:
1) A API key has been entered
2) There are published languages and that 'transifex_languages' has been successfully retrieved and saved to WP.
![wordpress-plugin-ui](https://cloud.githubusercontent.com/assets/974299/12056884/9ea6055c-aef0-11e5-8a43-efb9c06e13e6.jpg)

**Comment by samuelchan22** [comment]
@matthewjackowski @diegobz For the Language URLs, one other option is do what WP does with the Avatar settings in `/wp-admin/options-discussion.php`. 

* Make it it's own section.
* By default, have one checkbox for enabling or disabling an option (e.g. enable avatars).
* When the checkbox is checked, reveal additional options (e.g. avatar style). 
* Use radio buttons instead of the dropdown (but un-nested) to select options.

So something like this...

![image](https://cloud.githubusercontent.com/assets/2788702/12059420/9bb044e2-af0f-11e5-97be-9f2b5b0a5236.png)

Dropdowns take up less room, but in our case, I think radio buttons give us the needed space to explain what each option means.

**Comment by matthewjackowski** [comment]
Here's the latest pic:
![image](https://cloud.githubusercontent.com/assets/974299/12125043/d777d2a0-b39d-11e5-990b-585a02ee9531.png)

**Comment by matthewjackowski** [comment]
Some things to keep in mind...that we might want to revisit...
the source language and list of languages can only be updated via Live publishing...
the language code textboxes actually only control what appears in the url...
therefore the default Transifex codes are reported via HREFLANG

Having re-installed this many times over the past few weeks...IMHO it's important that the user fully setups up Live, translates, and publishes languages before attempting to use this functionality.

**Comment by matthewjackowski** [comment]
So I implemented a nag message that alerts the user when transifex_languages is out of date.  The plugin will check this on every refresh when is_admin == true
This has the side effect of appearing immediately before an api key is entered since transifex_languages is effectively null.  Depending on the copy we use this might be a great way to get the user to fill out their API key.
![image](https://cloud.githubusercontent.com/assets/974299/12306947/539a9986-b9f1-11e5-9ba4-27b3181eaa15.png)

**Comment by samuelchan22** [comment]
@matthewjackowski Here's some text you can use for States 1 to 3. We probably don't need something for State 4. Stuff in brackets are links.

1. ```<strong>Thanks for installing the Transifex Live WordPress plugin!</strong> [Add your API key] to make translations live for your site.```

2.  ```*Yoda voice* A problem with the Transifex Live plugin, there was. A transmission [to us send], and happy to assist you we would be.```
**Note:** Link to our contact page. I hope no one ever sees this but it'll be a fun easter egg. 

3. ```Looks like there were some changes to your published languages. Please reinstall the Transifex Live plugin.```

A couple thoughts:

- We should make all off these notices dismissable. Otherwise, we'll be *that* annoying plugin with the persistent notices :smile:  
- After writing / reading the message for State 3, I'm leaning towards having a sync button instead. I don't think explaining what a sync button does will be difficult.

**Comment by matthewjackowski** [comment]
So for #2 a concrete example of when this could fail legitimately is if the server is not able to make external calls.  This is a fairly common setup when securing WP.  People will definitely see this message.

**Comment by matthewjackowski** [comment]
Added 'Sync' button...it will trigger a reload of transifex_languages and mappings *only*.
![image](https://cloud.githubusercontent.com/assets/974299/12357311/009303a6-bb5c-11e5-9a0b-e1dff727f330.png)

**Comment by samuelchan22** [comment]
Here's the updated UI :)

![wp-1](https://cloud.githubusercontent.com/assets/2788702/12369504/5c0577fe-bbad-11e5-9bc4-2c81aefa5456.png)
![wp-2](https://cloud.githubusercontent.com/assets/2788702/12369505/5c251640-bbad-11e5-8db4-907fe0a63912.png)
![wp-3](https://cloud.githubusercontent.com/assets/2788702/12369506/5c31dad8-bbad-11e5-8d87-cc011ba7f9b8.png)

**Comment by matthewjackowski** [comment]
Updated UI
![image](https://cloud.githubusercontent.com/assets/974299/12387642/cb3a6fb8-bd82-11e5-9eb4-bbeb3be3ab65.png)

![image](https://cloud.githubusercontent.com/assets/974299/12387649/e1379e8a-bd82-11e5-85f0-152777a26dd0.png)

**Comment by matthewjackowski** [comment]
![image](https://cloud.githubusercontent.com/assets/974299/12400542/9022dc46-bdd5-11e5-8f7e-4306629041aa.png)

**Comment by samuelchan22** [comment]
Updated text: https://docs.google.com/a/indifex.com/document/d/12du_-51wb5XrjmvBu3KoechrrQsjSZs6xOYwnDraM44/edit?usp=sharing

I've added a few comments pointing to examples of similar formatting that already exists in WP by deafult.

**Comment by diegobz** [comment]
@samuelchan22 Can you change the permission setting of the gdocs?

**Comment by diegobz** [comment]
@matthewjackowski `Enable HREFLANG` should be set by default, IMHO. I'm not really sure if we need an option to disable/enable that at all TBH.

**Comment by matthewjackowski** [comment]
Here is gdoc image... @samuelchan22 please keep all feedback in github moving forward so we can avoid permission issues
![image](https://cloud.githubusercontent.com/assets/974299/12409145/467e895e-be1c-11e5-9f8e-3e6be1cc0f1d.png)

**Comment by matthewjackowski** [comment]
@diegobz So I assume by this "Enable HREFLANG should be set by default," you mean 'default' = "after an API key has been entered and transifex_languages has been loaded and after a rewrite option is specified"

**Comment by matthewjackowski** [comment]
Also fyi...the title on the admin page no longer matches the plugin name on Wordpress.org.  On WP it says "Transifex Live Translation Plugin" however here it is called "Transifex Live WordPress Plugin"...it might be a good idea to be consistent.  I would advise against using 'WordPress' for any plugin branding see http://wordpressfoundation.org/trademark-policy/

**Comment by matthewjackowski** [comment]
![image](https://cloud.githubusercontent.com/assets/974299/12411001/35702344-be2f-11e5-8469-327f52134b98.png)

**Comment by mikegianno** [comment]
Mind me, a little UX thingy: You could also add "All" as an option in the "Use Language/region-specific URLs For" field ;)

**Comment by matthewjackowski** [comment]
Brilliant!  added 'all' (which checks all the other checkboxes) thanks @mikegianno

**Comment by matthewjackowski** [comment]
all comments implemented...please open a new issue for further UI revisions
