### ISSUE TITLE
Admin color fields disabled

### ISSUE THREAD

**Issue by matthewjackowski** [transifex/transifex-live-wordpress#40]
The color fields should be disabled / grayed out until the checkbox is selected.

**Comment by samuelchan22** [comment]
@matthewjackowski Another option is to remove the checkbox all together and simply have the color fields with a set of default colors. If the user changes the colors, we'd then assume they want to use custom colors and update their language picker when they hit Save. It might actually make things a lot simpler, though I'm sure if that's possible from the technical side of things. What do you think?

**Comment by matthewjackowski** [comment]
Well, the checkbox actually does something important which is signal that the plugin should be overriding the settings in Live.  By removing it altogether, that would imply that the plugin would always override and the Live settings would no longer matter.

**Comment by matthewjackowski** [comment]
'Disabling' the controls is technically possible...however currently the form uses a very basic HTML forms that doesn't support 'interactive forms'. While I *could* roll-my-own disable css and javascript...it would be better to refactor the form and use jquery form library or a SPA.  I just need to understand the level of interactivity required

**Comment by matthewjackowski** [comment]
Color fields have been removed.
