### ISSUE TITLE
When I save changes, I should only see one success message.

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#49]
![image](https://cloud.githubusercontent.com/assets/2788702/12186120/9d27f5b8-b554-11e5-91be-4345edbdee09.png)

**Comment by matthewjackowski** [comment]
@samuelchan22  So what happens when you just change the colors and not any of the other settings?  You want it still to say 'settings' have changed?

**Comment by matthewjackowski** [comment]
So something I just found when running acceptance tests...the colors db data was not getting cleared.  Even if you uninstalled the plugin.  That might have made it appear as if the colors had changed.

**Comment by matthewjackowski** [comment]
colors have been dropped...so this issue is no longer relevant
