### ISSUE TITLE
Custom language codes should be preserved after resyncing with Transifex published languages

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#56]
We should expose language codes from Transifex, so people know what they have overwritten. See `pt_BR` example on image. This is probably not the best UI, but if should do the work until the get a designer to change all this. :)

![screen shot 2016-02-29 at 3 56 49 pm](https://cloud.githubusercontent.com/assets/711654/13413129/14ea777a-defd-11e5-8b56-047a38f7095f.png)

**Comment by diegobz** [comment]
One someone changes the URL code for a language, right now it's necessary to visit the permalinks page to flush its cache. We should take care of it automatically for the user.

**Comment by matthewjackowski** [comment]
@diegobz @samuelchan22 Current copy for nag popup is: "Refreshing languages will replace your current codes with those from Transifex Live. Continue?"
What should this be given the above function.

**Comment by matthewjackowski** [comment]
@samuelchan22 The copy has been moved to the template...you can update it here: https://github.com/transifex/transifex-live-wordpress/blob/devel/includes/admin/transifex-live-integration-settings-template.php#L57
