### ISSUE TITLE
When I hit the "refresh languages list" button, the "Your changes to the settings have been saved!" message appears

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#59]

**Comment by matthewjackowski** [comment]
@samuelchan22 what do you want it to say instead?

**Comment by samuelchan22** [comment]
Let's have it say "Languages list updated!"

And for these, should we use the standard admin notices?

**Comment by matthewjackowski** [comment]
I think standard admin notices makes sense.

**Comment by matthewjackowski** [comment]
![image](https://cloud.githubusercontent.com/assets/974299/12445045/f24c3024-bf16-11e5-96dd-76d29a78450b.png)
