### ISSUE TITLE
Refresh languages list button not working

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#60]
I published a new lang from live and it’s showing up in the jsonp file but not in the plugin even after clicking the Refresh languages list button and refreshing the page.

https://cdn.transifex.com/1c7a03562b5c4b59bbd319b7afd6ecae/latest/languages.jsonp
https://www.transifex.com/dunder-mifflin/wp-dev/

**Comment by matthewjackowski** [comment]
https://www.youtube.com/watch?v=CjV-u1NnpQs
