### ISSUE TITLE
Recents Posts links in the wordpress side menu do not obey Language URL structure

### ISSUE THREAD

**Issue by diegobz** [transifex/transifex-live-wordpress#61]
Screenshot taking while mouse-hovering the fist link of the `Recent posts` widget.

![screen shot 2016-01-19 at 4 58 52 pm](https://cloud.githubusercontent.com/assets/711654/12436947/67cd67a8-bece-11e5-8565-a0e590d3afad.png)

**Comment by matthewjackowski** [comment]
https://www.youtube.com/watch?v=f84BEG2a_bQ

**Comment by diegobz** [comment]
:+1:
