### ISSUE TITLE
Hreflang on homepage (/) are not right.

### ISSUE THREAD

**Issue by diegobz** [transifex/transifex-live-wordpress#62]
It keeps pointing to `/el/hello-world-2` page instead of `/el/`

view-source:http://wpliveplugin.onpressidium.com/

**Comment by matthewjackowski** [comment]
https://www.youtube.com/watch?v=f84BEG2a_bQ

**Comment by diegobz** [comment]
Visiting http://wpliveplugin.onpressidium.com/ and looking the the page source I can find that all href links point to the main url `/`. Language code is not being 'prepended'.

![screen shot 2016-01-20 at 7 03 42 am](https://cloud.githubusercontent.com/assets/711654/12452584/084ec652-bf44-11e5-9e5a-53f0cf92e3a7.png)

Same with other paths too.
![screen shot 2016-01-20 at 7 06 57 am](https://cloud.githubusercontent.com/assets/711654/12452710/bccf4dea-bf44-11e5-80d6-83239c5aa6cb.png)

**Comment by matthewjackowski** [comment]
I think I know how to build a reverse lookup for the more general case.  But that will take some doing.  Created a patch for just this specific issue.
