### ISSUE TITLE
Some internal generated WP links do not obey Language URL structure 

### ISSUE THREAD

**Issue by diegobz** [transifex/transifex-live-wordpress#65]
- [ ] Menu (Sample-page house-hover)

![screen shot 2016-01-20 at 7 11 47 am](https://cloud.githubusercontent.com/assets/711654/12452937/c3edf292-bf45-11e5-9a0a-7b6d28e64269.png)

- [ ] Archived widget (January 2016 mouse-hover)

![screen shot 2016-01-20 at 7 17 56 am](https://cloud.githubusercontent.com/assets/711654/12452986/062d03be-bf46-11e5-8ef7-5a20e19a99d1.png)

- [ ] Categories widget (ασδφ mouse-hover)

![screen shot 2016-01-20 at 7 17 28 am](https://cloud.githubusercontent.com/assets/711654/12452979/0182146c-bf46-11e5-9496-51c75ad7f6b9.png)

**Comment by diegobz** [comment]
@matthewjackowski I guess the Menu bullet item is the most pressing one.

**Comment by matthewjackowski** [comment]
These are controlled by the default Wordpress widgets

**Comment by matthewjackowski** [comment]
So data for menu items is stored like this in the database (below) so there must be a place where this object reference is being reversed generally (before the widget is rendered).
![image](https://cloud.githubusercontent.com/assets/974299/12531062/a3c842fc-c1a6-11e5-91bd-5a10a62d69ae.png)
