### ISSUE TITLE
Textdomain name should be plugin slug

### ISSUE THREAD

**Issue by fxbenard** [transifex/transifex-live-wordpress#7]
Following wpcs :

The textdomain should be the same as the plugin slug, so here transifex-live-wordpress
It shouldn't be using a variable as well

**Comment by matthewjackowski** [comment]
Ok, I'll revisit this.  I had to change slug per Wordpress rules.  Thanks @fxbenard

**Comment by matthewjackowski** [comment]
Changed to match 'transifex-live-integration' which is the slug used in the plug repository.
