### ISSUE TITLE
Implement support for subdomains

### ISSUE THREAD

**Issue by diegobz** [transifex/transifex-live-wordpress#72]
- [ ] Language/region URL options are shown only if one valid option is chosen form the dropdown menu.
- [ ] Sub-directory options only appear if that option is chosen.
- [ ] Hreflang should reflect the language subdomains/subdirectories available in every existing page.

![img_20160121_102005](https://cloud.githubusercontent.com/assets/711654/12490404/3afcebce-c02a-11e5-9db1-916428b38bf5.jpg)

**Comment by matthewjackowski** [comment]
![image](https://cloud.githubusercontent.com/assets/974299/12499526/34f7b7d2-c060-11e5-9aaf-e381cd387f93.png)

**Comment by matthewjackowski** [comment]
![image](https://cloud.githubusercontent.com/assets/974299/12499618/fe1d009a-c060-11e5-98e6-89b8bdcf2272.png)

@diegobz

**Comment by matthewjackowski** [comment]
With new dropdown...the follow rules change:
hreflangs will inject into the site on option 2,3
subdomain module enabled on option 2
rewrite module enabled on option 3 and at least 1 type checkbox option

**Comment by matthewjackowski** [comment]
For edge cases where the 'lang' param may not get set...hreflangs now only renders the 'source' language since it can't be sure that other urls are valid.
