### ISSUE TITLE
Add support for BCP 47 codes in HREFLANG

### ISSUE THREAD

**Issue by matthewjackowski** [transifex/transifex-live-wordpress#75]
Currently HREFLANGS reference the same locale id as used in the URL path...instead it should use correct web standardized code.

**Comment by matthewjackowski** [comment]
Added a textbox for hreflang code...currently user will need to specify the code.  It is only used for hreflangs.

**Comment by diegobz** [comment]
Ok nice. Let's make a first step helping people to get the correct language code. I think just turning the language code from `pt_BR` to `pt-br` for the hreflang field by default would work for now.
