### ISSUE TITLE
Show different help text for Subdomains

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#79]
1. When the Subdomain option is selected, show different help/intro text in the Language/region Codes section. I can give you the text, just need you to make the help text two separate strings so we can show different text depending on the selection in the dropdown.
2. When the Subdomain option is selected, hide the line that says "Having trouble getting language/region-specific URLs working..."

**Comment by matthewjackowski** [comment]
@samuelchan22 Sounds good, please give final copy.

**Comment by samuelchan22** [comment]
@matthewjackowski All the text can be found here in the Google doc below (anyone with the link can view it). As I was making edits, I realized other text needed to change too, so anything highlighted should be updated inside the plugin. And note that the final section title which currently says "Language/region Codes" should also change when the Subdomain option is selected.

https://docs.google.com/document/d/12du_-51wb5XrjmvBu3KoechrrQsjSZs6xOYwnDraM44/edit?usp=sharing

**Comment by matthewjackowski** [comment]
@samuelchan22 One change here...this bit 'If you’ve set up language subdomains...'
I think we should explain more about this, maybe provide a link...but as it stands it is unclear if this is something that can be done in Wordpress or by the plugin (it actually is neither the subdomains would need to be setup by whoever controls the DNS).

**Comment by samuelchan22** [comment]
@matthewjackowski How about "If you've already set up language domains on your site..."?

Maybe we just include something in the docs? We could link to something else, but it'd point somewhere outside of Tx.

**Comment by matthewjackowski** [comment]
I think it's ok to point it somewhere else...but if it's covered elsewhere specifically in the docs that's fine too...just as long as it's clear here that the plugin (or Wordpress) will not enable your domains. So more like: "If you've already set up language domains on your site (this has to be done outside of the plugin)..."

**Comment by matthewjackowski** [comment]
Or actually...here's a thought...since we are showing different text for subdomains...maybe add labels to the transifex_languages data to indicate the function.
ie
Please setup a subdomain like this -> el.transifex.com
Greek       |     el
Please setup a subdomain like this -> zh_CN.transifex.com
Chinese (China)  |  zh_CN

This is important because many people will override the default Tx language codes...and it's clearer how todo this.

**Comment by samuelchan22** [comment]
Your text suggestion works, let's use it! We can add something to the docs too.

**Comment by matthewjackowski** [comment]
I *think* this is resolved
