### ISSUE TITLE
Notify users when languages are not published

### ISSUE THREAD

**Issue by diegobz** [transifex/transifex-live-wordpress#84]
If there are no languages published for the Live resource, show a warning/notice to the user about in the plugin admin page.

It may be misleading when users don't have translations available yet, but expects to see them in the WP plugin admin interface to continue setting things up.

**Comment by matthewjackowski** [comment]
Please provide copy for this.

**Comment by samuelchan22** [comment]
How about this:

Before setting up language/region-specific URLs, please be sure you have [published translations](http://docs.transifex.com/live/quick-start-guide/#publish-translations) from Transifex Live.

**Comment by samuelchan22** [comment]
Closing because it's done / implemented slightly differently with the new 1.2.1.
