### ISSUE TITLE
Translate "Plugins/Themes"

### ISSUE THREAD

**Issue by dovy** [transifex/transifex-live-wordpress#9]
Transifex Live is based on per-site translation. I would love to base it on per-product translation.

Example, I have an open-source framework used by hundreds of thousands of users world-wide. We have been using Transifex for 2 year now. However, I'd love to offer Transifex live for developers to make translations within the app.

The problem is the app is embedded within their products on a variety of websites and a variety of versions. So we would need to bind the key not to the URL, but the "version" and "product."

If you could make this happen, I have 7500 developers to start testing this overnight. I'd help you build it, and I'd send people to you as well.  :)

**Comment by fxbenard** [comment]
+1

**Comment by diegobz** [comment]
Hey @dovy, I'm trying to wrap my mind around what you are suggesting. If you could elaborate a bit more, that would be great, mainly the following part:

`So we would need to bind the key not to the URL, but the "version" and "product."`

**Comment by matthewjackowski** [comment]
Going to close this as 'wontfix'. @dovy or @fxbenard I'm happy to reopen and chat more about this if you are still keen on it.
