### ISSUE TITLE
Change Check / Save buttons behaviors

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#95]
After entering your API key, if:

Valid API key and there are published languages, then:
- Show the success message 
- Hide the Save button next to the field
- Enable the bottom Save button

Valid API key and no languages are published, then:
- Show an error message (current link is broken)
- Keep the top button as Check.
- Keep the bottom Save button deactivated.

Invalid API key, then:
- Show an error message below the field (right now, no error message is shown and the top Save button is still clickable)
- Keep the top button as Check.
- Keep the bottom Save button deactivated.

**The bottom Save button will be the only Save button on the page and it saves everything.**

**Comment by matthewjackowski** [comment]
![](https://raw.githubusercontent.com/transifex/transifex-live-wordpress/devel/sample-ui/wordpress-admin-ui.gif)
