### ISSUE TITLE
Add the Sync Languages button back

### ISSUE THREAD

**Issue by samuelchan22** [transifex/transifex-live-wordpress#98]
Add the Sync Languages button back under the list of locales. Right now, the languages list in the plugin doesn’t (immediately?) match what’s published through Live.

![image](https://cloud.githubusercontent.com/assets/2788702/13021682/4c969ee8-d191-11e5-99db-db7ea299e28e.png)

**Comment by matthewjackowski** [comment]
Please post the API key that doesn't match.

**Comment by matthewjackowski** [comment]
The context here is this:
step 1 publish some languages in Live
step 2 setup the plugin (you should see those languages)
step 3 go back to Live and remove a language
step4 in the plugin click the refresh languages button
result: new languages overwrite in UI but are not saved
step 5 click the 'Save Changes' button to finalize

**Comment by matthewjackowski** [comment]
![](https://raw.githubusercontent.com/transifex/transifex-live-wordpress/devel/sample-ui/refresh-languages-ui.gif)
